In [6]:
import numpy as np

RGD = [19, 7, 4]
IAO = [9, 1, 15]

first_matrix_2d = np.array([[19, 7, 4], [9, 1, 15]])
print(first_matrix_2d.shape)
print(first_matrix_2d.ndim)

first_matrix = first_matrix_2d

print('first_matrix')
for row in first_matrix:
    print(row)

(2, 3)
2
first_matrix
[19  7  4]
[ 9  1 15]


In [7]:
2023-4-0o067 == [2, 0, 2]
2023-4-0o067 == [0, 6, 7]

second_matrix_2d = np.array([[2, 0, 2], [0, 6, 7]])
print(second_matrix_2d.shape)
print(second_matrix_2d.ndim)

second_matrix = second_matrix_2d

print('second_matrix')
for row in second_matrix:
    print(row)

(2, 3)
2
second_matrix
[2 0 2]
[0 6 7]


In [8]:
print(first_matrix)
print(second_matrix)

[[19  7  4]
 [ 9  1 15]]
[[2 0 2]
 [0 6 7]]


In [9]:
array_first_matrix = np.array(first_matrix)
array_second_matrix = np.array(second_matrix)

third_matrix = (array_first_matrix + array_second_matrix)

print('third_matrix')
for row in third_matrix:
    print(row)

third_matrix
[21  7  6]
[ 9  7 22]


In [10]:
array_first_matrix = np.array(first_matrix)

fourth_matrix = (array_first_matrix * 2)

print ('fourth_matrix')
for row in fourth_matrix:
    print(row)

fourth_matrix
[38 14  8]
[18  2 30]


In [12]:
second_matrix = np.array(second_matrix)
second_matrix_T = second_matrix.T

fifth_matrix = (second_matrix.T)

print ('fifth_matrix')
for row in fifth_matrix:
    print(row)

fifth_matrix
[2 0]
[0 6]
[2 7]


In [13]:
third_matrix = np.array(second_matrix)
third_matrix_T = third_matrix.T

third_matrix = third_matrix.T

print('third_matrix')
for row in third_matrix:
    print(row)

third_matrix
[2 0]
[0 6]
[2 7]


In [15]:
array_third_matrix = np.array(third_matrix)
array_fifth_matrix = np.array(third_matrix)

sixth_matrix = (array_third_matrix + array_fifth_matrix)

print('sixth_matrix')
for row in sixth_matrix:
    print(row)

sixth_matrix
[4 0]
[ 0 12]
[ 4 14]


In [16]:
array_third_matrix = np.array(third_matrix)

sum_third_matrix = np.sum(third_matrix)

print(sum_third_matrix)

17


In [17]:
seventh_matrix = np.zeros ((2, 3))

print('seventh_matrix')
for row in seventh_matrix:
    print(row)

seventh_matrix
[0. 0. 0.]
[0. 0. 0.]
